name: Auto Merge Release PRs

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
    paths-ignore:
      - ".github/**"

jobs:
  auto-merge:
    if: startsWith(github.head_ref, 'sync/')
    uses: personaclick/workflow/.github/workflows/reusable-auto-merge-pr.yaml@master
    secrets:
      appSecret: ${{ secrets.VERSIONER_SECRET }}
    with:
      appId: ${{ vars.VERSIONER_ID }}
